# fly.toml app configuration file generated for frosty-star-5890 on 2023-06-07T17:37:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "frosty-star-5890"
primary_region = "ams"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
