# fly.toml app configuration file generated for shy-glade-4054 on 2023-06-05T13:11:19+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shy-glade-4054"
primary_region = "ams"

[env]
  PORT = "8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
