
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2NDg3MTgxMzFmYzdkYzQ1OTYwMzIyZDAiLCJpYXQiOjE2ODY2NTIyODksImV4cCI6MTY4NjY1NTg4OX0.VI47U9ppalmlJwyoi9nKYIih-b1oMUDUqc6mgwWaV6M

{
  "title": "test",
  "author": "test",
  "url": "test",
  "likes": 5
}
